# http server config
httpServer:
  host: "localhost"

# web3 config
web3:
  provider: "<web3 provider url [http/https]>"

# paymaster config
paymaster:
  paymasterAddress: "0x<address>"
  signatureKey: "0x<privateKey>"

# bundler config
bundler:
  privateKeys: ["0x<privateKey1>", "0x<privateKey2>", "0x<privateKey3>"]
